### PR TITLE
Feature notifications announce

### PR DESCRIPTION
**Pull request by jonathanbossenger**
This PR addresses ticket https://meta.trac.wordpress.org/ticket/6373

Slack: Grant Joe and Brian slack /here access for #feature-notifications.

### CODE REVIEW

**Comment by StevenDufresne** [comment]
LGTM, ready to merge?

**Comment by jonathanbossenger** [comment]
Yes, please. Thanks @StevenDufresne

**Comment by StevenDufresne** [comment]
Merged. See https://meta.trac.wordpress.org/ticket/6373.

**Comment by jonathanbossenger** [comment]
Thanks @StevenDufresne

**Pull request closed without merging**
