### PR TITLE
Translate: Add some components into tabs in the right sidebar

### PR DESCRIPTION
**Pull request by amieiro**
Following the [work made in the gp-translations-helper](https://github.com/GlotPress/gp-translation-helpers/pull/148), the current PR adds 4 tabs (Meta, Discussion, History, Other locales) in the right sidebar of each translation.

Following the discussion in this PR to [add CSS to convert translate.wordpress.org to full width](https://github.com/WordPress/wordpress.org/pull/111), the current PR needs to increase the page width, to be able to have these 4 tabs, so it changes the maximum width from 1200px to 1600px, and some breakpoints. In the screenshots below, you can see the differences.

These screenshots were taken in a screen with a 1920x1080 resolution.

## New tabs

This is the current translation space (1200 px. max width):

10-before

And this is the new space with the new 4 tabs (1600 px. max width):

When it becomes narrower, the text on the tabs becomes shorter:

The new breakpoint to do both panels (center and right sidebar) full width is 1024px:

image

### Meta tab

The default tab has the current information from this right sidebar.

image

### Discussion tab

The discussion tab has all the discussions related with this translation. You can replay and/or start a new discussion from this tab.

image

### History tab

The history tab has all the translations for the current original and locale.

image

### "Other locales" tab

The "Other locales" tab has all the current translations for the current original and other locales. You can copy any translation from this tab.

image

## New width

This PR changes the maximum width from 1200px to 1600px. In the next screenshots, you can see the differences between the current situation and the proposed one. You can get more context in [this PR](https://github.com/WordPress/wordpress.org/pull/111).

### [Main page](https://translate.wordpress.org/)

**Before**

01-before

**After**

### [Stats page](https://translate.wordpress.org/stats/)

This is the only page whose content does not change, but the width of the translation header does.

**Before**

02-before

**After**

### [Consistency page](https://translate.wordpress.org/consistency/)

**Before**

03-before

**After**

### [Consistency page result](https://translate.wordpress.org/consistency/?search=Original&set=gl%2Fdefault&project=)

**Before**

04-before

**After**

### [Core list](https://translate.wordpress.org/locale/gl/default/wp/)

**Before**

05-before

**After**

### [Plugin list](https://translate.wordpress.org/locale/gl/default/wp-plugins/)

**Before**

06-before

**After**

### [Plugin translation status overview](https://translate.wordpress.org/locale/gl/default/stats/plugins/)

**Before**

07-before

**After**

### [A plugin (WooCommerce) translation overview](https://translate.wordpress.org/locale/gl/default/wp-plugins/woocommerce/)

**Before**

08-before

**After**

### [Translation list (stable branch)](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/gl/default/?filters%5Btranslated%5D=yes&filters%5Bstatus%5D=current)

**Before**

09-before

**After**

### [One translation](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/gl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=15033085&filters%5Btranslation_id%5D=100066162)

**Before**

10-before

**After**

### CODE REVIEW

**Comment by akirk** [comment]
This in combination with the latest version of https://github.com/GlotPress/gp-translation-helpers works well except for a visual glitch in Firefox 109.0:
117-glitch

**Comment by akirk** [comment]
Just retested and the visual bug is gone, well done!

**Comment by akirk** [comment]
I applied the updated patch and the sidebar doesn't work for me:

Screenshot 2023-02-13 at 21 12 42

It is [visually broken and shows no content](https://translate.wordpress.org/projects/wp-plugins/friends/dev/de/default/?filters%5Boriginal_id%5D=13590346&filters%5Bstatus%5D=either&filters%5Btranslation_id%5D=95823313), even if there is [a discussion on the dedicated page](https://translate.wordpress.org/projects/wp-plugins/friends/dev/13590346/de/default/):

Screenshot 2023-02-13 at 21 12 36

**Comment by akirk** [comment]
Backtracking, if I also checkout https://github.com/GlotPress/gp-translation-helpers/pull/160 then it works!

It still shows 0 entries for 7 seconds [on this page](https://translate.wordpress.org/projects/wp-plugins/friends/dev/de/default/?filters[original_id]=13590346&filters[status]=either&filters[translation_id]=95823313):

slow-load

Is it possible to show some loading indicator instead of `(0)`? Maybe just `(...)` or no parentheses?

**Comment by amieiro** [comment]
I forgot to mention you have to use https://github.com/GlotPress/gp-translation-helpers/pull/160. 
I think the best option is to remove the `(0)` text, because with this approach we reduce the tab width, so we avoid problems with the space in the tabs.

**Comment by amieiro** [comment]
I have removed the default `(0)` text in the tabs [here](https://github.com/GlotPress/gp-translation-helpers/pull/160/commits/9c212f39f80fdd783acee64a252b688053d79039), so now the end user only sees the number when it is loaded using the Ajax response.

**Comment by akirk** [comment]
Great that works for me!

**Comment by amieiro** [comment]
This PR has been deployed, and I have written a [post](https://make.wordpress.org/polyglots/2023/02/20/components-into-tabs-in-the-right-sidebar/) to inform to the community.

**Pull request closed without merging**
