### PR TITLE
Add a new tab to merge the "History", "Other locales" and "Translation Memory" tabs

### PR DESCRIPTION
**Pull request by amieiro**
## Problem

Currently, we have 5 tabs in the right sidebar to show different information:
- Meta.
- Discuss.
- History.
- Other locales.
- Translation memory (TM).

image

These tabs take up a lot of horizontal space with small devices and/or screens, showing tabs with only a few letters and without the number of elements, with a bad usability.

image

## Solution

This PR merges the content from the "History", "Other locales"  and "TM" in a new tab, called "Others", removing the three previous tabs.

image

This PR adds "summary" elements, so the user could show or hide the different elements. This PR remembers the status of each summary (opened or closed) when you change to another row.

image

This PR also solves a problem with the "Other locales" UI, reported [here](https://meta.trac.wordpress.org/ticket/7124).

**Problem**

image

**Solution** (singular): [Example](https://translate.wordpress.org/projects/wp/6.1.x/ar/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=15420267&filters%5Btranslation_id%5D=101428768)

image

**Solution** (plural): [Example](https://translate.wordpress.org/projects/wp/6.1.x/ar/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=15418382&filters%5Btranslation_id%5D=101426762)

image

And it resolves and overflow problem in the "History" table:

**Problem**

image

**Solution**

image

## Testing instructions

To test this PR, you need to use the branch from this [gp-translation-helpers' PR](https://github.com/GlotPress/gp-translation-helpers/pull/179). 

To test this PR, you have to access to some projects with:
- 0 or some elements in the "Translation memory" summary.
- 0 or some elements in the "Other locales" summary. 
- 0 or some History summary. 

You need to check some of these combinations to be sure all work as expected.

### CODE REVIEW

**Comment by akirk** [comment]
Do I also need to have a specific version of GlotPress? For me it looks like this:
Screenshot 2023-07-26 at 14 31 21

For consistency, should the "Other locales" be called "Other languages" now that we have more space?

**Comment by amieiro** [comment]
> Do I also need to have a specific version of GlotPress? For me it looks like this: Screenshot 2023-07-26 at 14 31 21
> 
> For consistency, should the "Other locales" be called "Other languages" now that we have more space?

You don't need a specific version of GlotPress. This PR moves the content from 3 tabs (Translation memory, Other locales and History) to a new one (Others) (1), maintaining the **TM** and the **Other Locales** at the bottom (2).

I hope that in the medium term we will be able to remove the elements at the bottom, but it is something I want to discuss with the community.

image

Related with the "Other locales" name, we always talk about "locales", not "languages", so I think this is the correct term. E.g., you can see it at https://translate.wordpress.org/

image

**Review by trymebytes — COMMENTED** [review]
> I think we could make these titles bold too, so it's consistent with the font weight for "Translation Memory" title.
Screenshot 2023-07-27 at 14 42 18

> I also get a JS error on loading the translations page

```
translation-suggestions.js?ver=1690463937:232 Uncaught TypeError: Cannot read properties of undefined (reading '16071546-106939859')
    at copyTranslationMemoryToSidebarTab
```

**Comment by amieiro** [comment]
Added the loading indicator 

image

**Comment by trymebytes** [comment]
I tested again ensuring that the `gp-translation-helpers` plugin is on the `tab-others` branch and the js errors do not appear anymore, apparently I was not on the right branch for  `gp-translation-helpers`

**Review by trymebytes — APPROVED** [review]
Works for me!

**Comment by akirk** [comment]
@amieiro will rebase this and we'll merge it then

**Comment by amieiro** [comment]
I close this PR, as it has been deployed at translate.wordpress.org

**Pull request closed without merging**
