### PR TITLE
Support profile - move security settings onto separate screen

### LINKED ISSUE #26: Move Account settings on to separate screen
> I think it would make sense to split the "Account" subsection that has Email/Password onto a new tab, and list that along with 2FA on that page.
> https://github.com/WordPress/wporg-two-factor/issues/15#issuecomment-1316376334

Breaking this off of #15 since it's a distinct task, and something that needs to be done in the `wporg-support` theme.

- [x] Create new Edit Account screen at https://wordpress.org/support/users/me/edit/account/
- [x] Populate screen with custom UI
- [x] Update Rosetta forums with same changes as main forums
- [x] Move Account settings from https://wordpress.org/support/users/me/edit/ to new screen -- staged in https://github.com/WordPress/wordpress.org/pull/114 but needs to wait until we launch for all users. Or maybe move it all to Profiles instread? Will still need to have the password/lang/etc settings removed from forums, unless ignoring them for now.
- [x] Update `Your password can be changed via...` link on `https://profiles.wordpress.org/{username}/profile/edit/group/1/` -- `wp-content/themes/profiles.wordpress.org/members/single/profile/edit-custom-general.php`

### PR DESCRIPTION
**Pull request by iandunn**
WIP

Fixes https://github.com/WordPress/wporg-two-factor/issues/26

### Regular Profile:

Screenshot 2023-09-18 at 12 55 55 PM

### Forum Profile

Screenshot 2023-09-18 at 12 57 31 PM

### CODE REVIEW

**Comment by iandunn** [comment]
@dd32, @pkevan, @tellyworth :  this pr creates a new `https://wordpress.org/support/users/{username}/edit/account/` page.  that works in conjunction with the [ui-stub](https://github.com/WordPress/wporg-two-factor/tree/ui-stub) branch in `wporg-two-factor`, which renders the `wporg-two-factor/settings` block into new page. that block would use REST API requests like Dion is building in https://github.com/WordPress/two-factor/pull/504 to save the 2FA settings, and  Core `users` endpoint to save email/password/language.

the text is just rough stubs and there's no design, but take a look at the code for both branches and let me know if you think this is a good architecture to build on

**Comment by pkevan** [comment]
I'm not deeply familiar with the profiles part, but seems like a sensible way to approach this initially.

**Comment by iandunn** [comment]
I've committed the parts that we can deploy now in 4db5f38 and `r19711-dotorg`, so now the branch just has the parts that need to wait until we launch everything for users.

**Comment by StevenDufresne** [comment]
I think we may need another path to security settings.

Logged in, when I click "Edit Profile", I land on https://profiles.wordpress.org/{username}/profile/edit/ which doesn't have any references to security settings. I would have to already know the settings is in our "Forum profiles".

Should we add a section to the General tab that leads directly to 2fa?


Screenshot 2023-09-15 at 2 06 45 PM

I'm not sure if that's the best language or link treatment :).

**Comment by pkevan** [comment]
We probably also want to change the label/link in the Forum profile from `Edit Account` to be more descriptive too
Screenshot 2023-09-15 at 08 23 50

**Comment by iandunn** [comment]
> change the label/link in the Forum profile from Edit Account to be more descriptive too

🤔 Do you have any ideas? It was named "Account" because previously the email/password settings were in a section of the profile page named "Account"

Renaming it to "Security" makes sense for the 2FA settings, but I don't think users would expect that for email. Maybe "Account Settings" instead of "Edit Account" ?

**Comment by iandunn** [comment]
> Should we add a section to the General tab that leads directly to 2fa?

What do you think about this?

Screenshot 2023-09-15 at 10 01 34 AM

That way we include "Security", with might catch folks eyes while they're scanning, but it still has "password" and "two-factor authentication". I'm also open to having a sections for each, though.

**Comment by StevenDufresne** [comment]
Yeah, that looks good to me.

**Comment by pkevan** [comment]
> > change the label/link in the Forum profile from Edit Account to be more descriptive too
> 
> 🤔 Do you have any ideas? It was named "Account" because previously the email/password settings were in a section of the profile page named "Account"
> 
> Renaming it to "Security" makes sense for the 2FA settings, but I don't think users would expect that for email. Maybe "Account Settings" instead of "Edit Account" ?

It's just labelled `Security` on WP.com, although I agree it's somewhat confusing when it contains email, although don't think it's a big issue - might be good for consistency.

**Comment by iandunn** [comment]
🤔 Changing the menu label would also entail changing the rewrite rule and links to the page.

I don't personally think it's worth it, but I'm not opposed to it either. I'd rather not tack that onto this PR, though, do you mind opening another issue for it?

**Pull request closed without merging**
