### PR TITLE
Bust cache for new full site editing filter

### PR DESCRIPTION
**Pull request by apeatling**
Bust cache for new full site editing filter

### CODE REVIEW

**Comment by adamwoodnz** [comment]
Sorry but I'm confused by this. The [changes to add the new filter](https://github.com/WordPress/wordpress.org/pull/85) appear to be all php, how does busting the JS and CSS cache help with this?

**Comment by apeatling** [comment]
The final changeset is here, you can see new JS and CSS build files: https://meta.trac.wordpress.org/changeset/11963

**Comment by apeatling** [comment]
I'm not super familiar with how this all works, but looking at past commits, this is what's needed.

**Comment by adamwoodnz** [comment]
> The final changeset is here, you can see new JS and CSS build files: https://meta.trac.wordpress.org/changeset/11963

Ah makes more sense now, thanks

**Comment by adamwoodnz** [comment]
Fixed in https://meta.trac.wordpress.org/changeset/11965

Thanks!

**Pull request closed without merging**
