### PR TITLE
Add filter to allow filtering the head tags used

### PR DESCRIPTION
**Pull request by sc0ttkclark**
Allow customization of the head tags used by the wporg-developer theme.

### CODE REVIEW

**Comment by dd32** [comment]
The need for this isn't immediately obvious to me, @sc0ttkclark Is there any meta ticket related to this or any direct need for it on developer.w.org?

**Comment by sc0ttkclark** [comment]
No this was in my work when I was attempting to use this theme for a phpdoc/wp parser project. I continue working on that project but whether this gets closed won't affect my current plan which was to abstract much of the logic in this theme and release it as something that can run on any theme

**Comment by dd32** [comment]
@sc0ttkclark  Apologies on ^. We migrated to a `trunk` main branch a while ago, but due to this repo's structure it wasn't a rename. Due to some unrelated things it's caused the `master` branch to be deleted and closed/invalidated your PR in the process.

Please feel free to either rebase upon trunk and create a ticket, or just leave it closed, up to you.

**Comment by sc0ttkclark** [comment]
I may do that but I've since abandoned using this theme and have been working on a refactor of the logic that is used by the theme. At this point I was thinking of doing a block theme or at least something I can define some new blocks/templates with a plugin and throw it onto any existing theme like a bbPress template system works. Haven't gotten that far yet and I'm not sure yet when I'll get that going. Maybe mid 2022... time is fun :)

**Pull request closed without merging**
